Accept SENSU_API_KEY in addition to SENSU_USER and SENSU_PASSWORD
sensu/sensu-flow pull request #30
Opened 2022-03-14 12:47 UTC by mhuysamen

2022-03-17 16:19 UTC, kmf commented
@calebhailey / @jspaleta anyone?

2022-06-23 21:39 UTC, jspaleta commented
Testing now,

Question for you... are you using this script locally or as a github action?

If your using it as a github action we'll need to expose the new env_var as a settable option for the github action.

2022-06-23 21:46 UTC, jspaleta requested changes

2022-06-23 21:46 UTC, jspaleta commented on sensuflow.sh
> +  status=$(${curl_command} --connect-timeout 30 -k -o /dev/null -s -w "%{http_code}" -X GET "${SENSU_BACKEND_URL}/auth/test" -u "${SENSU_USER}:${SENSU_PASSWORD}")
This test doesn't have to be skipped, it just needs to be modified to pass the api key as an http header.

2022-06-23 22:21 UTC, jspaleta approved these changes

2022-06-23 22:21 UTC, jspaleta commented on sensuflow.sh
> +  status=$(${curl_command} --connect-timeout 30 -k -o /dev/null -s -w "%{http_code}" -X GET "${SENSU_BACKEND_URL}/auth/test" -u "${SENSU_USER}:${SENSU_PASSWORD}")
Nope I'm wrong, the auth/test endpoint is only valid for user/pass.
Okay this looks good as it is. I'm going to do a follow up pr to refactor the github action definition that uses this script to allow for api key use

2022-06-23 22:21 UTC, merged